
name: 'microsoft_ads'
version: '1.0.0'
config-version: 2


models:
  microsoft_ads:
    materialized: table

vars:
  microsoft_ads:
    microsoft_ads_ad_performance_daily_report: "{{ ref('stg_microsoft_ads__ad_performance_daily_report') }}"
    microsoft_ads_ad_history: "{{ ref('stg_microsoft_ads__ad_history') }}"
    microsoft_ads_ad_group_history: "{{ ref('stg_microsoft_ads__ad_group_history') }}"
    microsoft_ads_campaign_history: "{{ ref('stg_microsoft_ads__campaign_history') }}"
    microsoft_ads_account_history: "{{ ref('stg_microsoft_ads__account_history') }}"